version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3333:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    tty: true

